name: Tests Connection to Azure from Github Actions using a Service Principal with a Secret
on: push

jobs:
  connect-with-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true
      - name: List Resources
        uses: azure/powershell@v1
        with:
          azPSVersion: latest
          inlineScript: |
            Get-AzResourceGroup | ft
