name: Connect with Secret
on: 
  push:
    paths:
      - '.github/workflows/with-secret.yml'

jobs:
  connect-with-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true
      - name: List Resource Groups
        uses: azure/powershell@v1
        with:
          azPSVersion: latest
          inlineScript: |
            Get-AzResourceGroup | ft
